/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parrcial3;

import com.google.gson.JsonArray;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

/**
 *
 * @author PC
 */
public class ParcialCorte3 extends javax.swing.JFrame {

    /**
     * Creates new form ParcialCorte3
     */
    public ParcialCorte3() {
        initComponents();
    }

    
    
    
    
    
    
   
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        campocedula = new javax.swing.JTextField();
        camponombre = new javax.swing.JTextField();
        campocorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonagregartxt = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        agregarJson = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Correo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        campocedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campocedulaActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese su cedula");

        jLabel2.setText("Ingrese su nombre");

        jLabel3.setText("Ingrese su correo");

        botonagregartxt.setText("Agregar en TXT");
        botonagregartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonagregartxtActionPerformed(evt);
            }
        });

        jButton1.setText("Cargar TXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Xml");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cargar Xml");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        agregarJson.setText("Agregar JSON");
        agregarJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarJsonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campocedula, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(camponombre)
                            .addComponent(campocorreo))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonagregartxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(agregarJson, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campocedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(botonagregartxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addComponent(agregarJson))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camponombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campocorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campocedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campocedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campocedulaActionPerformed

    private void botonagregartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonagregartxtActionPerformed
        
        
        
        String cedula = campocedula.getText();
        String nombre = camponombre.getText();
        String correo = campocorreo.getText();

        
        

        
        
        
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{cedula, nombre, correo});

        
        
        
        
        String rutaArchivo = "C:\\Users\\PC\\Documents\\NetBeansProjects\\parrcial3\\input.txt";

        
        
        
        
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(new File(rutaArchivo), true))) {
            bw.write(cedula + ", " + nombre + ", " + correo);
            bw.newLine(); 
            System.out.println("se guardaron los datos en el txt.");
        } catch (IOException e) {
            System.err.println("no se encontro la ruta: " + e.getMessage());
        }

        
        
        
        
      
        campocedula.setText("");
        camponombre.setText("");
        campocorreo.setText("");
        
        
        
    }//GEN-LAST:event_botonagregartxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        String rutaArchivo = "C:\\Users\\PC\\Documents\\NetBeansProjects\\parrcial3\\input.txt";
        File archivo = new File(rutaArchivo);


        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        
        
        

        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
               
                String[] datos = linea.split(", ");
                if (datos.length == 3) { 
                    model.addRow(datos);
                }
            }
            
        } catch (IOException e) {
            System.err.println("no se pudo leer el archivo: " + e.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    String cedula = campocedula.getText();
    String nombre = camponombre.getText();
    String correo = campocorreo.getText();

  
    
    
    
    try {
      
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        DocumentBuilder builder = factory.newDocumentBuilder();
        org.w3c.dom.Document doc = builder.newDocument();

       
        org.w3c.dom.Element root = doc.createElement("contactos");
        doc.appendChild(root);

        
        org.w3c.dom.Element contacto = doc.createElement("contacto");
        root.appendChild(contacto);

        
        org.w3c.dom.Element cedulaElem = doc.createElement("cedula");
        cedulaElem.appendChild(doc.createTextNode(cedula));
        contacto.appendChild(cedulaElem);

       org.w3c.dom.Element nombreElem = doc.createElement("nombre");
        nombreElem.appendChild(doc.createTextNode(nombre));
        contacto.appendChild(nombreElem);

        org.w3c.dom.Element correoElem = doc.createElement("correo");
        correoElem.appendChild(doc.createTextNode(correo));
        contacto.appendChild(correoElem);

       
        TransformerFactory transformerFactory = TransformerFactory.newInstance();
        Transformer transformer = transformerFactory.newTransformer();
        transformer.setOutputProperty(OutputKeys.INDENT, "yes");

        
        String rutaArchivo = "C:\\Users\\PC\\Documents\\NetBeansProjects\\parrcial3\\contactos.xml";
        File archivoSalida = new File(rutaArchivo);

        StreamResult result = new StreamResult(archivoSalida);
        DOMSource source = new DOMSource(doc);
        transformer.transform(source, result);

        

        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        
        
            campocedula.setText("");
            camponombre.setText("");
            campocorreo.setText("");
        

    } catch (ParserConfigurationException | javax.xml.transform.TransformerException e) {
        System.out.println("no  sepudo cargar el archivo");
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        try {
       
        String rutaArchivo = "C:\\Users\\PC\\Documents\\NetBeansProjects\\parrcial3\\contactos.xml";
        File archivo = new File(rutaArchivo);

        

        
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        DocumentBuilder builder = factory.newDocumentBuilder();
        org.w3c.dom.Document doc = builder.parse(archivo);
        doc.getDocumentElement().normalize();

        
         org.w3c.dom.NodeList listaContactos = doc.getElementsByTagName("contacto");

      
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        
        modelo.setRowCount(0);

        
        for (int i = 0; i < listaContactos.getLength(); i++) {
                 org.w3c.dom.Node nodo = listaContactos.item(i);
        if (nodo.getNodeType() == org.w3c.dom.Node.ELEMENT_NODE) {
            org.w3c.dom.Element elemento = (org.w3c.dom.Element) nodo;

                
                String cedula = elemento.getElementsByTagName("cedula").item(0).getTextContent();
                String nombre = elemento.getElementsByTagName("nombre").item(0).getTextContent();
                String correo = elemento.getElementsByTagName("correo").item(0).getTextContent();

               
                modelo.addRow(new Object[]{cedula, nombre, correo});
            }
        }

      

    } catch (Exception e) {
            System.out.println("no se encotro el XML");
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void agregarJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarJsonActionPerformed
        
    String cedula = campocedula.getText();
    String nombre = camponombre.getText();
    String correo = campocorreo.getText();

  

    try {
       
        com.google.gson.JsonObject contacto = new com.google.gson.JsonObject();
        contacto.addProperty("cedula", cedula);
        contacto.addProperty("nombre", nombre);
        contacto.addProperty("correo", correo);

       
        String rutaArchivo = "C:\\Users\\PC\\Documents\\NetBeansProjects\\parrcial3\\contactos.json";
        com.google.gson.JsonArray jsonArray = leerArchivoJson(rutaArchivo);

       
        
        jsonArray.add(contacto);

        
        com.google.gson.Gson gson = new com.google.gson.Gson();
        String jsonString = gson.toJson(jsonArray);

       
        try (java.io.FileWriter writer = new java.io.FileWriter(rutaArchivo)) {
            writer.write(jsonString);
            System.out.println("se guardon el archivo en la ruta");
        }

       
        campocedula.setText("");
        camponombre.setText("");
        campocorreo.setText("");

    } catch (java.io.IOException e) {
        System.out.println("no se escribio nada en el archivo");
    }
}


    private com.google.gson.JsonArray leerArchivoJson(String ruta) {
        com.google.gson.JsonArray jsonArray = new com.google.gson.JsonArray();
        java.io.File archivo = new java.io.File(ruta);

        if (archivo.exists()) {
            try (java.io.FileReader reader = new java.io.FileReader(archivo)) {
                com.google.gson.Gson gson = new com.google.gson.Gson();

                jsonArray = gson.fromJson(reader, com.google.gson.JsonArray.class);
                if (jsonArray == null) {
                    jsonArray = new com.google.gson.JsonArray(); 
                }
            } catch (java.io.IOException e) {
                System.out.println("no se pudo leer el archivo json");
            }
    }

    return jsonArray;
        
        
    }//GEN-LAST:event_agregarJsonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParcialCorte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParcialCorte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParcialCorte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParcialCorte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParcialCorte3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarJson;
    private javax.swing.JToggleButton botonagregartxt;
    private javax.swing.JTextField campocedula;
    private javax.swing.JTextField campocorreo;
    private javax.swing.JTextField camponombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
